server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/camunda-changelog.xml

camunda:
  bpm:
    default-serialization-format: application/json
